services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - portfolio-network

networks:
  portfolio-network:
    external: true
